---
title: "JDRF Sam figures from saved files"
author: "Dror Berel"
date: "`r Sys.Date()`"
output: 
  rmarkdown::html_vignette:
    keep_md: TRUE
    toc: yes
vignette: >
  %\VignetteIndexEntry{JDRF Sam figures from saved files}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr); select<-dplyr::select
library(magrittr)
library(purrr)
library(stringr)
library(tidyr)
library(tibble)
library(ggplot2)

library(mlr)
library(mlrCPO)

library(glmnet)
library(biobroom)
library(limma)
library(impute)

library(JDRF_CAV)
library(knitr)
library(cowplot)

```

## To do:
move following raw data files into package:   
load("Z:/R_rhino/JDRF_paper/data/comp_mat_20170930a.RData") # comp_overlap, comp_mat    
stats_disp_df<-read.csv('Z:/R_rhino/JDRF_paper/data/RMSE_benchmarking.csv') # Sam's past results


## Figure 2
```{r fig.height = 8, fig.width = 8}
stats_disp_df<-read.csv('Z:/R_rhino/JDRF_paper/data/RMSE_benchmarking.csv') # Sam's past results
# table(stats_disp_df$corrplot.n.clusters, stats_disp_df$feature.n)

ggplot(stats_disp_df) + 
  geom_line(aes(x=feature.n, y=RMSE_mean, color = as.factor(corrplot.n.clusters))) +
  # geom_hline(yintercept = rmse_direct)
  theme_bw() + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
 labs(title = 'Sensitivity analysis: RMSE for different pre-processing feature selection criteria',
       subtitle = 'Univariate: top_n, Clustering: 1-h')
```


## Figure 3: Heatmaps
```{r fig.height = 12, fig.width = 12}
load("Z:/R_rhino/JDRF_paper/data/comp_mat_20170930a.RData") # comp_overlap, comp_mat



####### Helper for figures: 1 (single), 3(multiple)
# cs <- c(0.75, 0.5, 0.4, 0.35, 0.3, 0.25, 0.2, 0.1, 0)
cs <- seq(0,0.75, 0.05)
# Ns <- c(5, 10, 15, 20, 25, 30, 35, 40, 50, 60)
Ns <- seq(5, 60, 5)
length(cs) * length(Ns) # 192 possible combinations

ps_df_alt <- expand.grid(cs, Ns)

## setup n=30, h=1-0.7
i_param1 <- 87
ps_df_alt[i_param1,c("Var1", "Var2")]

i_param2 <- 57
ps_df_alt[i_param2,c("Var1", "Var2")]

new <- ps_df_alt[,c("Var1", "Var2")]
new$comp <- comp_mat[i_param1,]

new <- new %>% 
  mutate(corr = 1-as.numeric(Var1),
         N    = Var2) 
new %>% 
  select(corr,N,comp) %>% 
  spread(key=N, value = comp)

i_comp <- length(cs)*length(Ns)*(i_param1-1) + i_param2 + 1
length(comp_overlap)
i_comp<-1
comp_overlap[i_comp][[1]][1]

# jumps of 192
single_models <- comp_overlap[seq(1, length(cs)*length(Ns)*length(cs)*length(Ns), length(cs)*length(Ns) )]



## Subset the models to regimes of parameters we want.
# h = 0.00 to 0.50
# N = 20   to 60
model_is <- new %>% 
  mutate(n_row = row_number()) %>%
  filter(corr <= 1.00 & corr >= 0.60) %>%
  filter(N    >= 20   & N    <= 50) %>%
  select(n_row) %>% as.list() %>% unlist()

length(model_is) # 63

new_disp <- new[model_is,]
single_models %>% length
fav_models <- lapply(model_is, function(x) {single_models[x]})
fav_models %>% length # 192
fav_model_analytes <- lapply(fav_models, function(x) {x[[1]][[3]]}) %>% unlist() %>% unique()




results_df <- data.frame(analyte = fav_model_analytes)
results_df$f_sig <- NA
results_df$f_all <- NA


for (i in 1:length(fav_model_analytes)) {
  
  # i = 30
  
  comp_an_present_sig <- sapply(fav_models, function(x) {fav_model_analytes[i] %in% x[[1]][[1]]})
  comp_an_present_all <- sapply(fav_models, function(x) {fav_model_analytes[i] %in% x[[1]][[3]]})
  
  comp_an_present_sig_b <- ifelse(comp_an_present_sig, 1, 0)
  comp_an_present_all_b <- ifelse(comp_an_present_all, 1, 0)
  
  results_df[i,"f_sig"] <- mean(comp_an_present_sig_b)
  results_df[i,"f_all"] <- mean(comp_an_present_all_b)
  
}
top_analytes <- results_df[order(results_df$f_all, decreasing = TRUE), "analyte"]
report_consistency <- results_df %>% arrange(desc(f_all))



## Compare the analytes from all of the model results
# library(RColorBrewer)
myColors <- c("#DDDDDD", "#56B4E9", "#0072B2")
names(myColors) <- c("Not in model", "In model, secondary analyte", "In model, primary analyte")

new_disp <- new
fav_models <- lapply(1:length(single_models), function(x) {single_models[x]})
fav_model_analytes <- lapply(fav_models, function(x) {x[[1]][[3]]}) %>% unlist() %>% unique()

results_df <- data.frame(analyte = fav_model_analytes)
results_df$f_sig <- NA
results_df$f_all <- NA

plot_list <- list()

########################
### all 488 analytes ###
########################
for (i in 1:length(fav_model_analytes)) {
  
  # i = 11
  # fav_model_analytes[1] %in% fav_models[[1]][[1]] # does the selected analyte appear in set y/n?
  # fav_model_analytes[1] %in% fav_models[[1]][[3]]
  
  comp_an_present_sig <- sapply(fav_models, function(x) {fav_model_analytes[i] %in% x[[1]][[1]]})
  comp_an_present_all <- sapply(fav_models, function(x) {fav_model_analytes[i] %in% x[[1]][[3]]})
  
  comp_an_present_sig_b <- ifelse(comp_an_present_sig, 1, 0)
  comp_an_present_all_b <- ifelse(comp_an_present_all, 1, 0)
  
  results_df[i,"f_sig"] <- mean(comp_an_present_sig_b)
  results_df[i,"f_all"] <- mean(comp_an_present_all_b)
  
  new_disp$an_present_sig_b <- factor(comp_an_present_sig_b, levels = c("0","1"))
  new_disp$an_present_all_b <- factor(comp_an_present_all_b, levels = c("0","1"))
  new_disp$`Analyte In Model` <- factor(comp_an_present_sig_b + comp_an_present_all_b, levels = c("0","1","2"))
  levels(new_disp$`Analyte In Model`) <- c("Not in model", "In model, secondary analyte", "In model, primary analyte")
  
  
  plot_list[[i]] <- ggplot() +
    geom_tile(data = new_disp,
              aes(x = N,
                  y = corr,
                  fill = `Analyte In Model`)) +
    labs(x = "Analytes per assay",
         y = "Min correlation in cluster", 
         title = str_sub(fav_model_analytes[i], start = 1, end = 30),
         fill  = "Analyte presence in models") +
    scale_fill_manual(name = "`Analyte In Model`", values = myColors) +
    scale_y_reverse() +
    theme(legend.position = "none",
          text = element_text(size=12),
          plot.title = element_text(size = 12))
  
}


#########  V1: Most consistent top_analytes[n_plots]
n_plots <- 16
top_analytes_results <- results_df$analyte[results_df$analyte %in% top_analytes[1:n_plots]]
plot_list_ordered <- plot_list[results_df$analyte %in% top_analytes[1:n_plots]]
plot_list_ordered <- plot_list_ordered[sapply(top_analytes[1:n_plots], function(x) { which(top_analytes_results %in% x)})]

pg <- plot_grid(plotlist = plot_list_ordered)
common_legend <- get_legend(plot_list[[18]] + theme(legend.position = "bottom"))
plot_grid(pg, common_legend, ncol = 1, rel_heights = c(1,.1))
pg




#########  V2: All analytes in the favorite model (18) / selected manually
fav_model_complete <- c("A...MFI_TIGIT_KLRG1p_TIGITp_CCR7n_Naive_CD8", 
                        "C...217607_x_at",
                        "C...220481_at",
                        "C...224543_at",
                        "C...225728_at",
                        "F...CCDC144A",
                        "F...JAGN1",
                        "F...SRRT",
                        "G...CCDC38",
                        "G...KIAA0319L",
                        "G...TOP3B",
                        "H...LRTOMT",
                        "H...PLA2G4B",
                        "H...ZNF596",
                        "J...MLXIP",
                        "K...ME11",
                        "P...MEdarkturquoise",
                        "cpep_auc2hr_log_baseline")

top_analytes_results <- results_df$analyte[results_df$analyte %in% fav_model_complete]
plot_list_ordered <- plot_list[results_df$analyte %in% fav_model_complete]
plot_list_ordered <- plot_list_ordered[sapply(fav_model_complete, function(x) { which(top_analytes_results %in% x)})]

pg <- plot_grid(plotlist = plot_list_ordered)
common_legend <- get_legend(plot_list[[18]] + theme(legend.position = "bottom"))
plot_grid(title, pg, common_legend, ncol = 1, rel_heights = c(1,.1))


## with title:
title <- ggdraw() + 
  draw_label("figure 3: Characteristics of analytes selected by tool", fontface = 'bold')
plot_grid(title, pg, common_legend, ncol = 1, rel_heights = c(1,.1))


pg

```




# ?. Session information
```{r }
sessionInfo()
```
